- name: Kill existing running instance
  docker:
    image=mlhamel.org
    state=killed

- name: Get the image
  shell: docker pull -a mlhamel/mlhamel.org

- name: Deploy container
  docker:
    image: mlhamel/mlhamel.org:latest
    insecure_registry: yes
    name: mlhamel.org
    ports: 8000:8000
    state: started

- name: creating nginx config
  template: src=nginx/mlhamel.org.conf dest=/etc/nginx/sites-available/mlhamel.org.conf
  notify: restart nginx

- name: enabling nginx config
  file: src=/etc/nginx/sites-available/mlhamel.org.conf
        dest=/etc/nginx/sites-enabled/mlhamel.org.conf state=link
  notify: restart nginx