- name: install needed stuff for docker
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - grub-legacy-ec2
    - linux-virtual
    - lxc
    - wget

- name: configure grub for docker
  lineinfile: dest=/boot/grub/menu.lst state=present
              line='# defoptions=console=hvc0 rootflags=nobarrier'
              regexp='# defoptions=console=hvc0'
  notify: regenerate grub menu

- name: Install new kernel
  apt: pkg={{ item }} state=latest update-cache=yes
  with_items:
    - linux-image-generic-lts-raring
    - linux-headers-generic-lts-raring
  register: kernel_result

- name: Reboot instance if kernel has changed
  command: reboot
  register: reboot_result
  when: "kernel_result|changed"

- name: Wait for instance to come online
  local_action: wait_for host= port=22 state=started
  when: "reboot_result|success"

- name: Add Docker repository key
  sudo: True
  apt_key: url="https://get.docker.io/gpg"

- name: Add Docker repository
  sudo: True
  apt_repository:
    repo: 'deb http://get.docker.io/ubuntu docker main'
    update_cache: yes

- name: Install Docker
  sudo: True
  apt: pkg=lxc-docker state=present
  notify: "Start Docker"

- name: install docker-py package
  pip: name=docker-py version=1.1.0